/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tomas Kranauskas (https://sketchfab.com/Tomasoo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/disassembled-v8-engine-block-3026bd87ca3945d6829d24c86ce695f0
title: Disassembled V8 Engine Block
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_2: THREE.Mesh
    mesh_3: THREE.Mesh
    mesh_4: THREE.Mesh
    mesh_5: THREE.Mesh
    mesh_6: THREE.Mesh
    mesh_7: THREE.Mesh
    mesh_8: THREE.Mesh
    mesh_9: THREE.Mesh
    mesh_10: THREE.Mesh
    mesh_11: THREE.Mesh
    mesh_12: THREE.Mesh
    mesh_13: THREE.Mesh
    mesh_14: THREE.Mesh
    mesh_15: THREE.Mesh
    mesh_16: THREE.Mesh
    mesh_17: THREE.Mesh
    mesh_18: THREE.Mesh
    mesh_19: THREE.Mesh
    mesh_20: THREE.Mesh
    mesh_21: THREE.Mesh
    mesh_22: THREE.Mesh
    mesh_23: THREE.Mesh
    mesh_24: THREE.Mesh
    mesh_25: THREE.Mesh
    mesh_26: THREE.Mesh
    mesh_27: THREE.Mesh
    mesh_28: THREE.Mesh
    mesh_29: THREE.Mesh
    mesh_30: THREE.Mesh
    mesh_31: THREE.Mesh
    mesh_32: THREE.Mesh
    mesh_33: THREE.Mesh
    mesh_34: THREE.Mesh
    mesh_35: THREE.Mesh
    mesh_36: THREE.Mesh
    mesh_37: THREE.Mesh
    mesh_38: THREE.Mesh
    mesh_39: THREE.Mesh
    mesh_40: THREE.Mesh
    mesh_41: THREE.Mesh
    mesh_42: THREE.Mesh
    mesh_43: THREE.Mesh
    mesh_44: THREE.Mesh
    mesh_45: THREE.Mesh
    mesh_46: THREE.Mesh
    mesh_47: THREE.Mesh
    mesh_49: THREE.Mesh
    mesh_50: THREE.Mesh
    mesh_51: THREE.Mesh
    mesh_52: THREE.Mesh
    mesh_48: THREE.Mesh
    mesh_53: THREE.Mesh
    mesh_54: THREE.Mesh
    mesh_55: THREE.Mesh
    mesh_56: THREE.Mesh
    mesh_57: THREE.Mesh
    mesh_58: THREE.Mesh
    mesh_59: THREE.Mesh
    mesh_60: THREE.Mesh
    mesh_61: THREE.Mesh
    mesh_62: THREE.Mesh
    mesh_63: THREE.Mesh
    mesh_64: THREE.Mesh
    mesh_65: THREE.Mesh
    mesh_66: THREE.Mesh
    mesh_67: THREE.Mesh
    mesh_68: THREE.Mesh
    mesh_69: THREE.Mesh
    mesh_70: THREE.Mesh
    mesh_71: THREE.Mesh
    mesh_72: THREE.Mesh
    mesh_73: THREE.Mesh
    mesh_74: THREE.Mesh
    mesh_75: THREE.Mesh
    mesh_76: THREE.Mesh
    mesh_77: THREE.Mesh
    mesh_78: THREE.Mesh
    mesh_79: THREE.Mesh
    mesh_80: THREE.Mesh
    mesh_81: THREE.Mesh
    mesh_82: THREE.Mesh
    mesh_83: THREE.Mesh
    mesh_84: THREE.Mesh
    mesh_85: THREE.Mesh
    mesh_86: THREE.Mesh
    mesh_87: THREE.Mesh
    mesh_88: THREE.Mesh
    mesh_89: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.94, -0.8, 2.78]}>
            <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
            <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
          </group>
          <group position={[-2.47, 4.76, 0.04]}>
            <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
            <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
          </group>
          <group position={[-2.16, 5.04, 2.18]}>
            <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
          </group>
          <group position={[-1.24, 4.42, -2.06]}>
            <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
          </group>
          <group position={[-0.96, -2.6, 2.15]}>
            <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
          </group>
          <group position={[-0.6, -3.08, 2.23]}>
            <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
          </group>
          <group position={[-0.61, -3.07, 1.9]}>
            <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
          </group>
          <group position={[1.1, -2.44, 2.21]}>
            <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
          </group>
          <group position={[0.76, -2.83, 2.03]}>
            <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} />
          </group>
          <group position={[0.47, -3.09, 2.35]}>
            <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
          </group>
          <group position={[-1.29, -2.39, -1.87]}>
            <mesh geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} />
          </group>
          <group position={[-0.7, -3.07, -1.81]}>
            <mesh geometry={nodes.mesh_13.geometry} material={nodes.mesh_13.material} />
          </group>
          <group position={[1.28, -2.31, -1.82]}>
            <mesh geometry={nodes.mesh_14.geometry} material={nodes.mesh_14.material} />
          </group>
          <group position={[0.75, -2.85, -2]}>
            <mesh geometry={nodes.mesh_15.geometry} material={nodes.mesh_15.material} />
          </group>
          <group position={[-1.44, -2.26, -0.54]}>
            <mesh geometry={nodes.mesh_16.geometry} material={nodes.mesh_16.material} />
          </group>
          <group position={[-0.95, -2.5, -0.48]}>
            <mesh geometry={nodes.mesh_17.geometry} material={nodes.mesh_17.material} />
          </group>
          <group position={[-0.94, -2.49, -0.79]}>
            <mesh geometry={nodes.mesh_18.geometry} material={nodes.mesh_18.material} />
          </group>
          <group position={[0.73, -2.54, -0.72]}>
            <mesh geometry={nodes.mesh_19.geometry} material={nodes.mesh_19.material} />
          </group>
          <group position={[1.3, -2.24, -0.52]}>
            <mesh geometry={nodes.mesh_20.geometry} material={nodes.mesh_20.material} />
          </group>
          <group position={[-1.29, -2.33, 0.78]}>
            <mesh geometry={nodes.mesh_21.geometry} material={nodes.mesh_21.material} />
          </group>
          <group position={[-0.95, -2.5, 0.83]}>
            <mesh geometry={nodes.mesh_22.geometry} material={nodes.mesh_22.material} />
          </group>
          <group position={[0.93, -2.44, 0.81]}>
            <mesh geometry={nodes.mesh_23.geometry} material={nodes.mesh_23.material} />
          </group>
          <group position={[0.64, -2.59, 0.6]}>
            <mesh geometry={nodes.mesh_24.geometry} material={nodes.mesh_24.material} />
          </group>
          <group position={[0.64, -2.59, 0.29]}>
            <mesh geometry={nodes.mesh_25.geometry} material={nodes.mesh_25.material} />
          </group>
          <group position={[2.32, 4.75, 0.13]}>
            <mesh geometry={nodes.mesh_26.geometry} material={nodes.mesh_26.material} />
            <mesh geometry={nodes.mesh_27.geometry} material={nodes.mesh_27.material} />
          </group>
          <group position={[2, 5.04, -2.01]}>
            <mesh geometry={nodes.mesh_28.geometry} material={nodes.mesh_28.material} />
          </group>
          <group position={[1.06, 4.5, 2.26]}>
            <mesh geometry={nodes.mesh_29.geometry} material={nodes.mesh_29.material} />
          </group>
          <group position={[-1.37, -8.6, 2.24]}>
            <mesh geometry={nodes.mesh_30.geometry} material={materials['Material.014']} />
          </group>
          <group position={[-2.43, 7.38, 1.92]}>
            <mesh geometry={nodes.mesh_31.geometry} material={nodes.mesh_31.material} />
          </group>
          <group position={[2.17, 7.15, 0.01]}>
            <mesh geometry={nodes.mesh_32.geometry} material={nodes.mesh_32.material} />
          </group>
          <group position={[0, 0, -5.35]}>
            <mesh geometry={nodes.mesh_33.geometry} material={nodes.mesh_33.material} />
          </group>
          <group position={[-0.09, -0.62, 4.14]}>
            <mesh geometry={nodes.mesh_34.geometry} material={nodes.mesh_34.material} />
          </group>
          <group position={[3.99, 0.93, 0.38]}>
            <mesh geometry={nodes.mesh_35.geometry} material={nodes.mesh_35.material} />
          </group>
          <group position={[-4.09, 0.94, 0.32]}>
            <mesh geometry={nodes.mesh_36.geometry} material={nodes.mesh_36.material} />
          </group>
          <group position={[-0.09, -3.32, -1.61]}>
            <mesh geometry={nodes.mesh_37.geometry} material={nodes.mesh_37.material} />
            <mesh geometry={nodes.mesh_38.geometry} material={nodes.mesh_38.material} />
          </group>
          <group position={[-0.08, 0.5, -4.25]}>
            <mesh geometry={nodes.mesh_39.geometry} material={nodes.mesh_39.material} />
            <mesh geometry={nodes.mesh_40.geometry} material={nodes.mesh_40.material} />
          </group>
          <group position={[-2.68, 2.17, 1.98]} scale={[0.99, 1, 1]}>
            <mesh geometry={nodes.mesh_41.geometry} material={nodes.mesh_41.material} />
            <mesh geometry={nodes.mesh_42.geometry} material={nodes.mesh_42.material} />
            <mesh geometry={nodes.mesh_43.geometry} material={nodes.mesh_43.material} />
          </group>
          <group position={[2.5, 2.18, -1.88]} scale={[1.09, 1, 1]}>
            <mesh geometry={nodes.mesh_44.geometry} material={nodes.mesh_44.material} />
            <mesh geometry={nodes.mesh_45.geometry} material={nodes.mesh_45.material} />
            <mesh geometry={nodes.mesh_46.geometry} material={nodes.mesh_46.material} />
          </group>
          <group position={[-0.09, -5.06, -1.22]}>
            <mesh geometry={nodes.mesh_47.geometry} material={materials['Material.008']} />
          </group>
          <group position={[0, -3.63, 0]}>
            <mesh geometry={nodes.mesh_49.geometry} material={nodes.mesh_49.material} />
            <mesh geometry={nodes.mesh_50.geometry} material={nodes.mesh_50.material} />
            <mesh geometry={nodes.mesh_51.geometry} material={nodes.mesh_51.material} />
            <mesh geometry={nodes.mesh_52.geometry} material={nodes.mesh_52.material} />
            <mesh geometry={nodes.mesh_48.geometry} material={nodes.mesh_48.material} />
          </group>
          <mesh geometry={nodes.mesh_53.geometry} material={nodes.mesh_53.material} />
          <mesh geometry={nodes.mesh_54.geometry} material={nodes.mesh_54.material} />
          <mesh geometry={nodes.mesh_55.geometry} material={nodes.mesh_55.material} />
          <mesh geometry={nodes.mesh_56.geometry} material={nodes.mesh_56.material} />
          <mesh geometry={nodes.mesh_57.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.mesh_58.geometry} material={nodes.mesh_58.material} />
          <group position={[-2.15, 3.88, 0]}>
            <mesh geometry={nodes.mesh_59.geometry} material={nodes.mesh_59.material} />
            <mesh geometry={nodes.mesh_60.geometry} material={nodes.mesh_60.material} />
            <mesh geometry={nodes.mesh_61.geometry} material={nodes.mesh_61.material} />
          </group>
          <group position={[-0.09, 5.16, 0]}>
            <mesh geometry={nodes.mesh_62.geometry} material={materials['Material.026']} />
            <mesh geometry={nodes.mesh_63.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.mesh_64.geometry} material={materials['Material.024']} />
            <mesh geometry={nodes.mesh_65.geometry} material={materials['Material.023']} />
            <mesh geometry={nodes.mesh_66.geometry} material={materials['Material.022']} />
          </group>
          <group position={[2, 3.88, -0.08]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.mesh_67.geometry} material={nodes.mesh_67.material} />
            <mesh geometry={nodes.mesh_68.geometry} material={nodes.mesh_68.material} />
            <mesh geometry={nodes.mesh_69.geometry} material={nodes.mesh_69.material} />
          </group>
          <group position={[0, 0, -0.02]}>
            <mesh geometry={nodes.mesh_70.geometry} material={nodes.mesh_70.material} />
          </group>
          <group position={[0, -4.72, 3]}>
            <mesh geometry={nodes.mesh_71.geometry} material={nodes.mesh_71.material} />
          </group>
          <group position={[0.18, -3.93, 2.01]}>
            <mesh geometry={nodes.mesh_72.geometry} material={nodes.mesh_72.material} />
          </group>
          <group position={[-0.37, -3.89, -1.8]}>
            <mesh geometry={nodes.mesh_73.geometry} material={nodes.mesh_73.material} />
          </group>
          <group position={[-0.05, -2.55, 0.85]}>
            <mesh geometry={nodes.mesh_74.geometry} material={nodes.mesh_74.material} />
          </group>
          <group position={[-0.24, -2.6, 0.61]}>
            <mesh geometry={nodes.mesh_75.geometry} material={nodes.mesh_75.material} />
          </group>
          <group position={[1.97, -0.28, 2.78]}>
            <mesh geometry={nodes.mesh_76.geometry} material={nodes.mesh_76.material} />
          </group>
          <group position={[1.97, 5.08, 2.28]}>
            <mesh geometry={nodes.mesh_77.geometry} material={nodes.mesh_77.material} />
          </group>
          <group position={[-1.63, -1.16, 2.3]}>
            <mesh geometry={nodes.mesh_78.geometry} material={nodes.mesh_78.material} />
          </group>
          <group position={[-1.63, -1.16, -1.02]}>
            <mesh geometry={nodes.mesh_79.geometry} material={nodes.mesh_79.material} />
          </group>
          <group position={[-1.63, -6.29, -1.93]}>
            <mesh geometry={nodes.mesh_80.geometry} material={nodes.mesh_80.material} />
          </group>
          <group position={[-1.63, -1.24, -1.9]}>
            <mesh geometry={nodes.mesh_81.geometry} material={nodes.mesh_81.material} />
          </group>
          <group position={[1.45, -1.24, -1.91]}>
            <mesh geometry={nodes.mesh_82.geometry} material={nodes.mesh_82.material} />
          </group>
          <group position={[1.43, -1.16, -1.03]}>
            <mesh geometry={nodes.mesh_83.geometry} material={nodes.mesh_83.material} />
          </group>
          <group position={[1.43, -1.16, 2.31]}>
            <mesh geometry={nodes.mesh_84.geometry} material={nodes.mesh_84.material} />
          </group>
          <group position={[-1.71, 7.09, 1.37]}>
            <mesh geometry={nodes.mesh_85.geometry} material={nodes.mesh_85.material} />
          </group>
          <group position={[1.56, 7.08, -1.13]}>
            <mesh geometry={nodes.mesh_86.geometry} material={nodes.mesh_86.material} />
          </group>
          <group position={[4, 0.92, -2.41]}>
            <mesh geometry={nodes.mesh_87.geometry} material={nodes.mesh_87.material} />
          </group>
          <group position={[-4.1, 0.94, 2.57]}>
            <mesh geometry={nodes.mesh_88.geometry} material={nodes.mesh_88.material} />
          </group>
          <group position={[-2.12, 5.08, 2.6]}>
            <mesh geometry={nodes.mesh_89.geometry} material={nodes.mesh_89.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
