/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Scuderia Morello (https://sketchfab.com/scudmorello)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/f6-boxer-engine-5700259eeb494b8f8a0b8f63486c59cc
title: F6 Boxer Engine
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_2: THREE.Mesh
    mesh_3: THREE.Mesh
    mesh_4: THREE.Mesh
    mesh_5: THREE.Mesh
    mesh_6: THREE.Mesh
    mesh_7: THREE.Mesh
    mesh_8: THREE.Mesh
    mesh_9: THREE.Mesh
    mesh_10: THREE.Mesh
    mesh_11: THREE.Mesh
    mesh_12: THREE.Mesh
    mesh_13: THREE.Mesh
    mesh_14: THREE.Mesh
    mesh_15: THREE.Mesh
    mesh_16: THREE.Mesh
    mesh_17: THREE.Mesh
    mesh_18: THREE.Mesh
    mesh_19: THREE.Mesh
    mesh_20: THREE.Mesh
  }
  materials: {
    Spada_1SG: THREE.MeshStandardMaterial
    blinn10SG: THREE.MeshStandardMaterial
    blinn6SG: THREE.MeshStandardMaterial
    lambert11SG: THREE.MeshStandardMaterial
    blinn14SG: THREE.MeshStandardMaterial
    blinn15SG: THREE.MeshStandardMaterial
    blinn3SG: THREE.MeshStandardMaterial
    blinn4SG: THREE.MeshStandardMaterial
    blinn5SG: THREE.MeshStandardMaterial
    initialShadingGroup: THREE.MeshStandardMaterial
    lambert10SG: THREE.MeshStandardMaterial
    lambert2SG: THREE.MeshStandardMaterial
    lambert3SG: THREE.MeshStandardMaterial
    lambert4SG: THREE.MeshStandardMaterial
    typeBlinn1SG: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.Spada_1SG} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.blinn10SG} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.blinn6SG} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.lambert11SG} />
        <mesh geometry={nodes.mesh_4.geometry} material={materials.blinn14SG} />
        <mesh geometry={nodes.mesh_5.geometry} material={materials.blinn15SG} />
        <mesh geometry={nodes.mesh_6.geometry} material={materials.blinn3SG} />
        <mesh geometry={nodes.mesh_7.geometry} material={materials.blinn4SG} />
        <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
        <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
        <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} />
        <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
        <mesh geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} />
        <mesh geometry={nodes.mesh_13.geometry} material={nodes.mesh_13.material} />
        <mesh geometry={nodes.mesh_14.geometry} material={nodes.mesh_14.material} />
        <mesh geometry={nodes.mesh_15.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.mesh_16.geometry} material={materials.lambert10SG} />
        <mesh geometry={nodes.mesh_17.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.mesh_18.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.mesh_19.geometry} material={materials.lambert4SG} />
        <mesh geometry={nodes.mesh_20.geometry} material={materials.typeBlinn1SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
